### ISSUE TITLE
Keep auth when reloading browser

### ISSUE THREAD

**Issue by Aadmaa** [n6g7/redux-saga-firebase#103]
For the example auth flow, when someone refreshes the browser, Firebase actually doesn't lose the auth, but this saga flow needs a tweak to capture that: just put a loginSuccess action after the yield put(syncUser(user)), as below:

function * syncUserSaga () {
  const channel = yield call(rsf.auth.channel)
  while (true) {
    const { user } = yield take(channel)
    if (user) {
      yield put(syncUser(user))
      **yield put(loginSuccess())**
    }
    else yield put(syncUser(null))
  }
}

**Comment by apaatsio** [comment]
But now it would dispatch the `loginSuccess()` action on *every page load* if the user has already logged in, right? But that's not what we want. Or what do you think adding `yield put(loginSuccess())` will accomplish that the `yield put(syncUser(user))` alone does not?

**Comment by n6g7** [comment]
@apaatsio is right:

- the role of `loginSuccess()` is to inform us that the user *just logged in successfully*
  - only dispatched after the user has clicked "Login", not necessarily on every page load
- `syncUser(user)` tells us that *the user is currently logged-in* (but might now have just logged-in if he refreshed the page).
  - automatically dispatched at each page load to let us know who is the current user

And actually `syncUser(user)` would always be dispatched just after `loginSuccess()`.

So `syncUser(user)` is single source of truth to know whether a user is logged-in, `loginSuccess()` is some sort of escape hatch in case you need to do something fancy.

Maybe the docs should be clearer about this, or the examples simplified. Do you guys have any suggestions for this? Maybe renaming those action creators?
