### ISSUE TITLE
Does database.patch(pathOrRef, data) support fanouts?

### ISSUE THREAD

**Issue by socceroos** [n6g7/redux-saga-firebase#110]
Fanouts as described here: https://firebase.googleblog.com/2015/10/client-side-fan-out-for-data-consistency_73.html

Having read the source code, I don't think the current implementation allows for calling patch (which maps to update) with a fanout object.

**Comment by n6g7** [comment]
Hi @socceroos, I've never used fanouts myself so I can't confirm whether it works but looking at the code it looks like [whatever `rsf.database.patch()` is called with is directly passed to the `update()` method of the ref](https://github.com/n6g7/redux-saga-firebase/blob/master/src/database.js#L33).

Have you tried using fanouts yourself?

**Comment by socceroos** [comment]
OK, so the problem I had was with patch() asking for a pathOrRef and additionally data - since the fanout contains the paths that will be updated it didn't make much sense. By setting pathOrRef to '/' I was able to get it working.
