### ISSUE TITLE
weird issue with channel

### ISSUE THREAD

**Issue by romk1n** [n6g7/redux-saga-firebase#114]
Hi, 

We have an interesting issue, when we login to the app very first time we don't get any `channel` updates. The example of the code we have is the following:

```
function* getSubscriptionStatus() {
  // waiting for root path to become available plus giving a chance to fully run
  try {
    yield delay(5000);
    const rootPath = yield select(selectRootPath);
    const channel = yield call(rsf.database.channel, `${rootPath}${dbPaths.configStatus}`);
    while (true) {
      const { value: status } = yield take(channel);
      if (status) {
        yield put(subscriptionStatus(status === 'active'));
      }
    }
  } catch (e) {
    return e;
  }
}
```

```
export default function* rootSaga() {
  yield [
    // omitted
    fork(getSubscriptionStatus),
  ];
}
```

If I logout and login back to the firebase it starts to work, any idea how to resolve this ?

Many Thanks.

**Comment by n6g7** [comment]
Hi Roman,

I con't see anything wrong in your code.
What does `selectRootPath` return? Can you `console.log(rootPath)` and verify that it is not null or undefined? What about `dbPaths.configStatus`?

**Comment by n6g7** [comment]
I'll close this for now, let me know if the problem persists.

**Comment by romk1n** [comment]
@n6g7 thanks for the reply. we figure it out the issue was that the path would change every time you login with a user. So when `fork`ing we needed to remember the effect and keep track of it. So in case of login with another user we would cancel an effect and create a new one.
