### ISSUE TITLE
Firestore off channel

### ISSUE THREAD

**Issue by henriqueweiand** [n6g7/redux-saga-firebase#124]
is it possible to cancel a channel event using the official firebase lib? for example:
```js
firebase
    .firestore()
    .collection(channelName)
    .off();
```
in fact, that way it did not work ... so I do not know what the correct form would be like by lib or not.

Could you tell me?

**Comment by n6g7** [comment]
Hey Henrique,

When using the official firebase lib you can listen for changes in a collection by doing something like this:
```js
const collectionRef = firebase.firestore().collection('...')
const unsubscribe = collectionRef.onSnapshot(snapshot => {
   // do whatever you want with the snapshot
})
```

You also detach the listener to stop listening for changes by simply calling `unsubscribe`.

-------

If you want to do the above using RSF you can fork a saga and stop it later:
```js
function * () {
  const task = yield fork(rsf.firestore.syncCollection, '...', {
    successActionCreator: (snapshot) => { ... },
    failureActionCreator: (error) => { ... }
  })

  // ...

  yield cancel(task)
}
```
