### ISSUE TITLE
How to use data type as reference in within a .firestore.channel?

### ISSUE THREAD

**Issue by henriqueweiand** [n6g7/redux-saga-firebase#132]
I recently noticed that there is a type for relationship between documents, but when trying to use within the scheme to get information with channel, the return does not seem to be correct, for example:

![captura de tela 2018-08-10 as 13 21 09](https://user-images.githubusercontent.com/6539492/43969372-4fc87afa-9ca0-11e8-914c-e5efd2ab3cbe.png)

![captura de tela 2018-08-10 as 13 17 27](https://user-images.githubusercontent.com/6539492/43969204-c334871e-9c9f-11e8-8071-1830f053eed2.png)

Is there any solution to get this data from the relation still inside the channel

**Comment by n6g7** [comment]
Hey Henrique, 

From what I've read I think the following should work:

```js
function* todosRootSaga() {
  yield fork(
    rsf.firestore.syncDocument,
    'todos/1',
    { successActionCreator }
  );
}

const successActionCreator = snapshot => {
  // snapshot is a DocumentSnapshot of 'todos/1'
  const data = snapshot.data()
  data.pacienteId // is a DocumentReference to your patient
}
```

- [DocumentSnapshot](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentSnapshot)
- [DocumentReference](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference)

Could you share a code example that details what doesn't works like you expect?
