### ISSUE TITLE
is createUserWithEmailAndPassword behavior correct?

### ISSUE THREAD

**Issue by henriqueweiand** [n6g7/redux-saga-firebase#138]
In a scenario where I am a user already logged in and would like to register another user inside, when calling the method **auth.createUserWithEmailAndPassword(email, password)**, it automatically register and log in. Is that correct? Should not you just do the registration?

**Comment by n6g7** [comment]
Hi Enrique,

Unfortunately this is how the underlying [`firebase.auth.Auth#createUserWithEmailAndPassword`](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#createUserWithEmailAndPassword) method works, and this behaviour is not controlled by RSF. :(

If you want to change this or to ask for another method to be added that would only register a new user without logging in, I suggest you open an issue on [Firebase JS SDK repo](https://github.com/firebase/firebase-js-sdk) and I'll be happy to add suporrt for it in RSF! :)
