### ISSUE TITLE
No read permission error gets silently swallowed

### ISSUE THREAD

**Issue by cbrwizard** [n6g7/redux-saga-firebase#147]
Hey, I was using this library for a firebase database channel, but it didn't trigger any actions on data change. After ditching this library and trying out my code I started getting permission errors like "Error: permission_denied at /stuff: Client doesn't have permission to access the desired data." After I changed the database rules, both my code and this library started working.

A conclusion: this library silently swallows read permission errors. Please don't do that, silent errors are evil [:

**Comment by n6g7** [comment]
Hi @cbrwizard,

Did you pass a `failureActionCreator` to the [`sync` method](https://redux-saga-firebase.js.org/reference/dev/database/#sync)? If you didn't then any error would have effectively been "silently swallowed".

Maybe that's a design mistake? i.e. when `failureActionCreator` is not passed then errors should be thrown.
I'll think about that but changing this behaviour now would be a breaking change.

**Comment by n6g7** [comment]
Thanks for the feedback.
I've now logged the error to the console so at least it's obvious that something happened. Also added a line to the docs to explain the behaviour better.
Hopefully this would have solved your problem. :)

**Comment by cbrwizard** [comment]
Hey we seem to have exactly the same issue now with errors being swallowed. Where do I put this `failureActionCreator` again? I can't see it in the docs

**Comment by n6g7** [comment]
Hey, can I ask:
- what version of the rsf are you using?
- are you seeing an error message ("The following error has been ignored because no `failureActionCreator` has been set:...") in the console?

`failureActionCreator` is a key in the second argument of [database.sync](https://redux-saga-firebase.js.org/reference/dev/database#sync) (and firestore.sync* too actually). It's true that the docs aren't very clear and there's not example. :(

Let me know if adding it solves your issue and we'll update the docs!

**Comment by cbrwizard** [comment]
What about other methods? Because we don't use sync. Also it seems that there were no errors in the console

**Comment by n6g7** [comment]
What methods are you using? Could you provide a reproduction script?

**Comment by cbrwizard** [comment]
Okay so I have checked almost every firestore method (except sync*) and all database methods. Firestore methods I've checked work fine, but in realtime db `sync` and `channel` methods doesn't handle missing permissions errors at all.
Using 0.15.0 version.

```
  yield fork(
    // @ts-ignore
    rsf.database.sync,
    'todos',
    {
      successActionCreator: setRecords,
      failureActionCreator: setUploadsNote,
    }
  )
  yield call(rsf.database.update, 'todos/1', {
    done: false, // yay, it's done now!
    label: 'Do this',
  });
```

```
path /todos {
  write() { true }
  read() { false }
}
```

What's expected: 
-[X] Update runs successfully
- [] Sync is triggered and should run `setUploadsNote` action as it fails on missing permissions
That action doesn't get triggered.

If you don't specify `failureActionCreator` I expect to see an error printed in console, but it doesn't.

When I switch `read` rules to `true` `setRecords` action gets successfully called. So I assume this is a bug in the `sync` implementation.

Next, `channel`.

```
  const channel = yield call(rsf.database.channel, 'todos');

  while(true) {
    const { value: todos } = yield take(channel);
    console.log(todos)
  }
```

```
path /todos {
  write() { false }
  read() { false }
}
```

When reading is prohibited, nothing gets printed in the console and there is no indication of a mission permissions error. When reading is allowed, `todos` get properly printed out to console.

Please fix these methods. I also think it might be related to https://github.com/n6g7/redux-saga-firebase/issues/197
