### ISSUE TITLE
Website down with 500 error

### ISSUE THREAD

**Issue by stasinua** [n6g7/redux-saga-firebase#170]
@n6g7 Just letting you know that https://redux-saga-firebase.js.org/ is down more than 30 minutes.
![image](https://user-images.githubusercontent.com/13312879/53511471-32679f00-3ac9-11e9-9292-24a54ae135f8.png)

**Comment by stasinua** [comment]
@n6g7 Website is UP. Closing.

**Comment by n6g7** [comment]
Hey @stasinua, thanks for letting me know!

It looks like there was [an issue with Netlify](https://www.netlifystatus.com/) earlier today but that it's fixed now, I'll keep an eye on the website.
