### ISSUE TITLE
storage.uploadFile does not return UploadTask

### ISSUE THREAD

**Issue by eugenio1590** [n6g7/redux-saga-firebase#177]
I am calling the 'storage.uploadFile' function and I get an error when trying to subscribe to the event channel. This is because the function returns an 'UploadTaskSnapshot' object. This is my code:

```
const task = yield call(reduxSagaFirebase.storage.uploadFile, file.serverPath, file)
console.log(task)
const channel = eventChannel(emit => task.on('state_changed', emit))
yield takeEvery(channel, function* callback(snapshot) {
  console.log(snapshot)
})
yield task
```

The image is saved in Firebase but I am going to display the progress bar with the information of the snapshot but in the task.

```
"firebase": "^5.9.1",
"redux-saga-firebase": "^0.15.0",
```

**Comment by eugenio1590** [comment]
I resolved it calling the function directly and wait for the task to finish at the bottom.
````
const task = reduxSagaFirebase.storage.uploadFile(file.serverPath, file)
const channel = eventChannel(emit => task.on('state_changed', emit))
yield takeEvery(channel, function* callback(snapshot) {
  console.log(snapshot)
})
yield task
````
It's important to update the documentation.

**Comment by n6g7** [comment]
Hi there,

Thanks for the feedback!

Unfortunately that's a side effect of `firebase.storage.UploadTask` having a [`then` method](https://firebase.google.com/docs/reference/js/firebase.storage.UploadTask#then), so redux-saga assumes it's a promise and [resolves it](https://github.com/redux-saga/redux-saga/blob/edd8f77b7886c858199ff2c23af571cec6477f8c/packages/core/src/internal/effectRunnerMap.js#L113).

So, as far as I can tell, your solution is correct, even though you lose the ability to properly test your saga. That's actually exactly [what I did in the example codebase](https://github.com/n6g7/redux-saga-firebase/blob/master/example/src/redux/sagas/storage.js#L20-L25) to go around this issue.

I'll update the docs, thanks!

**Comment by eugenio1590** [comment]
Yes, the test is difficult to with this change. But using a manual mock with jest for returning the correct answer, It worked for me. Thanks to you.
