### ISSUE TITLE
Documentation issue: Functions documentation doesn't load on the website

### ISSUE THREAD

**Issue by archiekd** [n6g7/redux-saga-firebase#180]
The url on the documentation for the function calling doesn't load due to an error with a className the url that doesn't work is https://redux-saga-firebase.js.org/reference/dev/functions/

Could this be fixed so that I can view the docs?

Thanks

**Comment by n6g7** [comment]
Ah good catch, thanks. I'll look into this!
In the meantime, you can read the docs in [markdown format](https://github.com/n6g7/redux-saga-firebase/blob/master/docs/reference/dev/functions.md).

**Comment by n6g7** [comment]
Fixed in https://github.com/n6g7/redux-saga-firebase/commit/f9c68ea86fd85a613b1f0a5f95502f897a72df39
https://redux-saga-firebase.js.org/reference/dev/functions/
