### ISSUE TITLE
FacebookAuthProvider.credential undefined

### ISSUE THREAD

**Issue by kwkatbabel** [n6g7/redux-saga-firebase#193]
rsf.auth.FacebookAuthProvider.credential(data.accessToken)

Using rsf with react-native-fbsdk. How can I get the FacebookAuthProvider.credential for facebook login?

**Comment by n6g7** [comment]
RSF doesn't re-export the auth providers, you can import directly from Firebase:
```js
import firebase from 'firebase'
const authProvider = new firebase.auth.FacebookAuthProvider()
```
For a full example, take a look at [the example app](https://github.com/n6g7/redux-saga-firebase/blob/master/example/src/redux/sagas/login.js).
