### ISSUE TITLE
AaU I can login with different methods

### ISSUE THREAD

**Issue by n6g7** [n6g7/redux-saga-firebase#24]
Not only popup, add:
- [x] [signInAnonymously](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInAnonymously)
- [x] [signInWithCredential](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInWithCredential)
- [x] [signInAndRetrieveDataWithCredential](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInAndRetrieveDataWithCredential)
- [x] [signInWithCustomToken](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInWithCustomToken)
- [X] [signInWithEmailAndPassword](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInWithEmailAndPassword)
- [x] [signInWithRedirect](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInWithRedirect)
- [x] [signInWithPhoneNumber](https://firebase.google.com/docs/reference/js/firebase.auth.Auth#signInWithPhoneNumber)

**Comment by sarovin** [comment]
and Phone Number sign-in? https://firebase.google.com/docs/auth/web/phone-auth

**Comment by n6g7** [comment]
@sarovin Good point, I just added it. :)
