### ISSUE TITLE
Support database queries for sorting/filtering

### ISSUE THREAD

**Issue by ryansully** [n6g7/redux-saga-firebase#34]
Currently all of the database methods accept a `path` string to define the Firebase database reference. Because of this, [sorting and filtering](https://firebase.google.com/docs/database/web/lists-of-data#sorting_and_filtering_data) features are not supported. If a ref could be passed to the method instead of a path, sorting and filtering could be defined before performing the database operation.

Ideally the database methods would support either a path string or a ref, either by separate methods or combined in the same ones?

**Comment by ryansully** [comment]
I have a modified version of `channel()` that I'm using now that supports either path or ref as the first argument, as well as support for other features like channel buffers, and returning the snapshot instead of `snapshot.val()` (in case you need access to other properties of the snapshot object).

I can submit a PR, but wanted to wait for #31 to be merged before digging in.

**Comment by n6g7** [comment]
Hi @ryansully, I love the idea, thank you for opening this. :)

I'd definitely welcome a PR to add this, however as you said it's probably better to wait for #31 to be merged. Should be ready sometime next week!

**Comment by n6g7** [comment]
I assume #41 fixes this so I'm closing this for now.
