### ISSUE TITLE
ERROR: regeneratorRuntime is not defined 

### ISSUE THREAD

**Issue by protoEvangelion** [n6g7/redux-saga-firebase#44]
After including Redux Saga Firebase as the docs suggest, I am getting a `regeneratorRuntime is not defined` error in my Chrome console.  Specifically it is complaining about the *first generator function* in my saga file.

```js
function* logIn(action) {
  ...
}
```

I was actually getting this error before but resolved it by adding `import 'regenerator-runtime/runtime'` in my saga file.

***Is there something else I need to do to prevent this error?***

**Comment by n6g7** [comment]
Hello @protoEvangelion 

Are you using webpack+babel to package your code? If so you'll need to include [`babel-polyfill`](https://babeljs.io/docs/usage/polyfill/) (which includes `regeneratorRuntime`) in your webpack config.

- Add it to your project dev dependencies: `yarn add --dev babel-polyfill`
- Update your webpack.config.js file:
  ```js
  module.exports = {
    [...]
    entry: ['babel-polyfill', './index.js'],
    [...]
  }
  ```

For a more complete example check out the [example app's config](https://github.com/n6g7/redux-saga-firebase/blob/master/example/webpack.config.js#L6).

Did that help?

**Comment by protoEvangelion** [comment]
@n6g7 Hey I think the problem was that I was using the package `webpack-blocks` to setup my webpack file.

I tried adding the `babel-polyfill` to my webpack.config however I still could not get it to function properly.

Thank you for your quick response and for trying to help!
