### ISSUE TITLE
support for updateProfile?

### ISSUE THREAD

**Issue by bentatum** [n6g7/redux-saga-firebase#48]
Any plans to add support for the methods here: https://firebase.google.com/docs/auth/web/manage-users

**Comment by n6g7** [comment]
Hi @bentatum,

TBH it's the first time I'm seeing these APIs so no, there is no plan to support those yet.
I can't commit on this feature in the near future but I'd be welcome a PR to add this. 😉

**Comment by gunn4r** [comment]
I could use these in the current project I'm on, so I'll look at creating a PR for this.

**Comment by dwilt** [comment]
@gunn4r any progress on this? I need it in my project too.

**Comment by gunn4r** [comment]
Nope! Completely forgot about it! haha. Thanks for the reminder. Added to my todo list. I'll shoot for a finished PR this weekend.

@dwilt

**Comment by dwilt** [comment]
@gunn4r Awesome, thanks!

**Comment by gunn4r** [comment]
Wasn't able to get to this this past weekend. I'll get to it as soon as I can but if anyone else wants to take it in the mean time, that's totally fine. :)

**Comment by n6g7** [comment]
This was added in https://github.com/n6g7/redux-saga-firebase/pull/111
