### ISSUE TITLE
Using the library Universally

### ISSUE THREAD

**Issue by rahulbasu710** [n6g7/redux-saga-firebase#64]
Loved the library. the simplicity and how it works in sync with Firebase is just marvellous.

I want to use it, but my library uses Universal or Isomorphic Node JS with React. So I was wondering how do I setup the `RSF library` so that preloaded server-side functions can be called with this so that we can `serve data universally` through the static functions thus decreasing initial load-time drastically.

Also what would be a way to move the firebaseconfig part to server so that we could use something like `firebase-admin`

**Comment by n6g7** [comment]
Hi Rahul,

That's a very interesting issue, thanks for bringing it up! I imagine you're not the only running into this. :)

Unfortunately, I have very little experience with isomorphic/universal apps so I don't know exactly what works or doesn't work when using RSF. Could you provide any error you're encountering as well as a code example?

As for the `firebase-admin` stuff, it looks like [admin.app.App](https://firebase.google.com/docs/reference/admin/node/admin.app.App) is very similar to [firebase.app.App](https://firebase.google.com/docs/reference/js/firebase.app.App) so I think you should be able to do something like:
```js
const admin = require('firebase-admin')
const ReduxSagaFirebase = require('redux-saga-firebase')

const app = admin.initializeApp({
  apiKey: 'aaabbbccc',
  authDomain: 'project.firebaseapp.com',
  databaseURL: 'https://project.firebaseio.com',
  projectId: 'project',
  storageBucket: 'project.appspot.com',
  messagingSenderId: '123456'
})
const rsf = new ReduxSagaFirebase(app)
```
And then use `rsf` as you usually would. Although I've never tried this before so I'm not 100% sure. Let me know if it works. :)

**Comment by rahulbasu710** [comment]
Hey Nathan, really sorry to have taken so long to get back to you. Well I was actually updating my repository with the other things. I shall try it tonight and integrate it with the rest of it. Your project is a very nice one and I guess eliminates the need to use RxJS for this. To give you a reference, this is the one I am integrating with [https://github.com/rahulbasu710/react-universal-subway_style](React Universal Subway Style)

Would love to collaborate!!

Thanks
