### ISSUE TITLE
Firestore support

### ISSUE THREAD

**Issue by n6g7** [n6g7/redux-saga-firebase#65]
- [x] Read / write
- [x] [Realtime updates](https://firebase.google.com/docs/firestore/query-data/listen)
- [x] [Queries](https://firebase.google.com/docs/firestore/query-data/get-data), [Order, Limit](https://firebase.google.com/docs/firestore/query-data/order-limit-data)
- [X] [Offline access](https://firebase.google.com/docs/firestore/manage-data/enable-offline): only [one method](https://firebase.google.com/docs/reference/js/firebase.firestore.Firestore#enablePersistence), use it like so:
  ```js
  function * saga () {
    const firestore = app.firestore()
    yield call([firestore, firestore.enablePersistence])
  }
  ```

**Comment by KamesCG** [comment]
I'll work on these tasks this week. I noticed plenty was added :)

In regards to offline access, if I'm understanding correctly that choice is made in the Firestore initialization settings. Redux Saga Firebase won't be able to influence whether it has access to offline mode or how to access those collections/documents differently.

Am I misunderstanding the documentation or missing something?

**Comment by n6g7** [comment]
@KamesCG I think you're right about offline access, there's only [one method](https://firebase.google.com/docs/reference/js/firebase.firestore.Firestore#enablePersistence) of interest. I probably should have read the docs before opening this issue!
I'll remove it from the list.

Looking forward to your PRs! 😉

**Comment by KamesCG** [comment]
I'll merge updates soon. Figuring out the best workflow still.

In regards to the "ref" conversation. It might help to simplify the function, while also introducing the ability to call sub-collections/documents directly from one ref constructor.

```
const branch = [
  collection,
  document,
  collection,
  document
]

  _getBranch (branch, service) {
    return [this.app[service](), ...branch].reduce((a, v, i)=> {
      return !i 
      ? v
      : i % 2
        ? a.collection(v)
        : a.doc(v)
    });
  }
}
```

Using the above function you can pass an array using the following pattern ['collection', 'document', 'collection', 'document'] and it will construct either a collection, document or sub-collection/document reference.

**Comment by darthneel** [comment]
@KamesCG I was curious if you were working on the [Realtime Updates](https://firebase.google.com/docs/firestore/query-data/listen) task yet. If not, I might give it a shot because I need that functionality for a project I'm working on. Thanks!

**Comment by KamesCG** [comment]
@darthneel Yes. I'm working on Realtime updates. That being said, the primary task is to finish/solidify the core API for retrieving collections/documents and the mechanisms around composing those into React components.

Realtime updates are a great feature, so that's definitely a priority for me though.

**Comment by n6g7** [comment]
@KamesCG I really like the recursive idea to get collection/document references, we could even accept dot-separated strings like `col1.doc1.col2.doc2`!
Do you want to open a PR with this change? Otherwise, I'll try to give this a go soon. :-)

Also I'm not sure what breaking changes you're talking about. Is that related to https://github.com/n6g7/redux-saga-firebase/pull/61?

@darthneel It doesn't look like @KamesCG has started implementing real-time updates yet in his PR so you can definitely give it a go.
Looking forward to your PR! :)

**Comment by n6g7** [comment]
@KamesCG I looked a bit more it and it seems all of the [built-in](https://firebase.google.com/docs/reference/js/firebase.firestore.Firestore#collection) [reference](https://firebase.google.com/docs/reference/js/firebase.firestore.Firestore#doc) [construction](https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference#collection) [methods](https://firebase.google.com/docs/reference/js/firebase.firestore.CollectionReference#doc) already accept slash-separated path to a collection / a document. So we certainly don't need the dot-separated strings and I don't think we need to support arrays either.
Getting a reference given an array is already as simple as:
```js
doc = rsf._getDocument(['col1', 'doc1'].join('/'))
col = rsf._getcollection(['col1', 'doc1', 'col2'].join('/'))
```

**Comment by KamesCG** [comment]
To clarify, I'm working on Realtime updates for a local project. Haven't pushed to repo yet.

In regards the recursive method for getting collection/documents the reasoning was a unified API for my React Component/Containers. My preference is minimize the amount of props I may have to pass in for the same "family" of components.

```
this.props.firestoreDocumentFilterGetRequest({
        metadata:{
          branch: [this.props.collection],
          delta: this.props.delta,
          filter: this.props.filter
        }
      })
```

and 

```
this.props.firestoreDocumentComposeGetRequest({
          metadata: {
            branch: [
              this.props.collection
            ],
            delta: this.props.delta,
            references: this.props.references
          }
        })
```

In my Sagas I map "references" props back into the "branch" for multiple requests during a Saga chain and I've found the single ref constructor to be more simple to reason about.

**Comment by n6g7** [comment]
@KamesCG @darthneel I think we're ready now!

- real-time updates are available through the [`firestore.syncCollection`](https://n6g7.github.io/redux-saga-firebase/reference/firestore#syncCollection) and [`firestore.syncDocument`](https://n6g7.github.io/redux-saga-firebase/reference/firestore#syncDocument) methods.
- sorting and filtering are [documented here](https://n6g7.github.io/redux-saga-firebase/guides/sorting-filtering).

I'll release v0.7 with these changes soon, let me know if you can think of any more features you'd like to see in future releases. :)

Thanks for the help!
