### ISSUE TITLE
TypeError: Cannot read property 'getCollection' of undefined

### ISSUE THREAD

**Issue by FSSDawid** [n6g7/redux-saga-firebase#68]
Hi there,
Just wanted to checkout your sagas for firestore but I can't seem to get it running
Getting this error:
` at rootSaga 
 at takeEvery 
 at getUsers 
 TypeError: Cannot read property 'getCollection' of undefined` 

code: 
`function* getUsers() {
	const snapshot = yield call(rsf.firestore.getCollection, 'users');
	let users;
	snapshot.forEach(user => {
		users = {
			...users,
			[user.id]: user.data()
		}
	});
	yield put(listSuccess(users));
}`

**Comment by n6g7** [comment]
Hi @FSSDawid,
which version are you using? The firestore features haven't been released yet, so unless you specified your dependency using a [github link](https://docs.npmjs.com/files/package.json#github-urls) you won't be able to use them.

I realise the docs site already lists those features even though they're not available yet, I'm going to look into fixing this.

I'll keep this issue open for now and let you know when the firestore features are released. ;)

**Comment by FSSDawid** [comment]
Hi @n6g7 I managed to figure out my problem :) 
I was missing the firestore import in rsf.
```
import firebase from 'firebase';
import 'firebase/firestore'; // This was missing :)
```
I'm using the version from git ;) and firebase 4.6.0
Thanks for the response.
