### ISSUE TITLE
package npm is not up to date 

### ISSUE THREAD

**Issue by ataliadvanstep** [n6g7/redux-saga-firebase#72]
I was unable to find out the firestore code in the package uploaded into npm.

npm install --save redux-saga-firebase

+ redux-saga-firebase@0.6.1

![image](https://user-images.githubusercontent.com/26287180/32519661-c14fbaf6-c40d-11e7-87be-47c8686cd144.png)

Is the package correctly uploaded ?

**Comment by n6g7** [comment]
Hi @ataliadvanstep, firestore hasn't made it to a released version yet, we're still [working on it](https://github.com/n6g7/redux-saga-firebase/issues/65).
I'll let you know when it's ready! :)

**Comment by ataliadvanstep** [comment]
ok thanks , I will follow up the other thread :-)
