### ISSUE TITLE
Example app module transform-runtime not found

### ISSUE THREAD

**Issue by TimMeade** [n6g7/redux-saga-firebase#74]
Getting this trying to run the 'yarn dev'.   I am on OSX and running node 9.1

**Comment by TimMeade** [comment]
yarn add babel-preset-stage-3 transform-runtime babel-transform-runtime seems to fix

**Comment by n6g7** [comment]
Hi @TimMeade, thanks for the report.

I can't reproduce this locally (on macOS 10.13.1 + node 9.1), `rm-rf node_modules && yarn && yarn dev` works fine for me. :(

Also `babel-preset-stage-3` is included in `babel-preset-stage-2` (which we're using) so I don't think adding it would change anything.

Could you provide detailed reproduction steps please? :)

**Comment by n6g7** [comment]
@TimMeade closing this for now, let me know if you're still having this issue and we'll re-open!
