### ISSUE TITLE
[best-practice] database.channel

### ISSUE THREAD

**Issue by shprink** [n6g7/redux-saga-firebase#76]
Hello,

thanks for your great work, I fell in love with it :)

I have questions regarding best practice on channels.

* How do you handle paths that contains a variable set only when auth is complete (e.g user.uid) ?
* How do you handle the unregistration => registration when changing user since `syncDashboardsSaga` is ony called once?

The following code does not work because `user` does not exist when loading the app (only populated when `auth.channel` respond)

```js
function* syncDashboardsSaga() {
  const user = yield select(state => state.auth.user);
  const channel = yield call(rsf.database.channel, `dashboards/${user.uid}`);

  while (true) {
    const { value } = yield take(channel);
    yield put(actions.dashboardsUpdate(value));
  }
}

export default function* dashboardsRootSaga() {
  yield fork(syncDashboardsSaga);
}
```

**Comment by shprink** [comment]
I managed to do what I wanted listening to the `syncUser` action.

https://github.com/n6g7/redux-saga-firebase/blob/520d70c493396304cd2dcc5e77d184918a639abb/example/src/redux/sagas/login.js#L41

**Comment by harvey56** [comment]
Hi @shprink ! I am trying to solve the same problem you had. Do you mind sharing how you did it ? I'm aware it goes a bit far back...

**Comment by shprink** [comment]
Old indeed. Sorry @harvey56 I can't help you :(
