### ISSUE TITLE
Trying to use firestore getting WEBPACK error.

### ISSUE THREAD

**Issue by TimMeade** [n6g7/redux-saga-firebase#77]
trying to use firestore.

I have auth working great using:

config = { my config }
firebase.initializeApp(config);
const reduxSagaFirebase = new ReduxSagaFirebase(firebase);

When I add firestore to it per the docs:
const reduxSagaFirebase = new ReduxSagaFirebase(firebase, firebase.firestore());

I get.

TypeError: __WEBPACK_IMPORTED_MODULE_0_firebase___default.a.firestore is not a function

Quite a bit of googling has turned up next to nothing.   Any ideas?

Thanks

**Comment by TimMeade** [comment]
Well of course 2 minutes after i try a different search.

Firestore is not included automatically.  Have to include it:

import firebase from 'firebase';
import 'firebase/firestore';

Compiles webpack fine now.

Closing as solved.

**Comment by n6g7** [comment]
Hey Tim,

Thanks for the feedback, I guess we can improve the docs to make this clearer.
Re-opening this to update the docs. :)

**Comment by n6g7** [comment]
@TimMeade I updated [the firestore docs](http://localhost:4000/redux-saga-firebase/reference/firestore), hopefully this should be clearer now. :)
