### ISSUE TITLE
Immutable Error 

### ISSUE THREAD

**Issue by sciphergfx** [n6g7/redux-saga-firebase#78]
Getting 'Immutable Error' in my reducer after calling the createUserWithEmailAndPassword function.
The response seem to return a promise, is there a way to sort this?

My code:

```js
export function * register (action) {
  const { email, password } = action

  // make the call to the api
  try {
    const response = yield call(reduxSagaFirebase.auth.createUserWithEmailAndPassword, email, password)

    yield put(RegisterActions.registerSuccess(response))
  } catch (error) {
    yield put(RegisterActions.registerFailure(error))
  }
}
```

**Comment by blacktea** [comment]
Getting same error with 
```
    const result = yield call(sagaFirebase.auth.signInWithEmailAndPassword, data.email, data.password)
```

**Comment by n6g7** [comment]
Hey guys, thanks for the bug report!
I'm a bit overwhelmed at work right now but I'll take a look at this soon!

**Comment by n6g7** [comment]
@sciphergfx I couldn't reproduce this error, either with `createUserWithEmailAndPassword` or `signInWithEmailAndPassword`. Could you provide the entire error and code example that fails?

Thanks!

**Comment by blacktea** [comment]
In my case this happened when Redux state was Immutable and I tried to put `user` object (returned by Firebase) directly into state. `user` object had references and stuff, so obviously Immutable could not serialize it.

Solution - let Firebase serialize it first:

Here is my setUser reducer
```
export const set = (state, action) => {
  const {user} = action
  let userClean = user ? user.toJSON() : null
  return state.merge({profile: userClean, isGuestUser: false})
}
```

**Comment by n6g7** [comment]
Ah cool, that explains it. :)

I'll keep this issue to add a section to the docs about using immutable.js.

**Comment by n6g7** [comment]
@sciphergfx @blacktea I've added a [section in the docs](https://n6g7.github.io/redux-saga-firebase/guides/immutable) to explain this issue. :)
