### ISSUE TITLE
firestore.addDocument need to assign specific document id.

### ISSUE THREAD

**Issue by TimMeade** [n6g7/redux-saga-firebase#82]
Current docs show:

_Adds a new document to this collection with the specified data, assigning it a document ID automatically_

Is there any current or planned means to assign a specific id?   For example: we want to create a staff document that matches to the auth document with the same id.

**Comment by TimMeade** [comment]
I'm going to close;  there is what i would call a workaround (or my lack of knowledge).

You can create the doc with a set.  So calling setDocument while passing id to collection will create doc with id.

yield call(rsf.firestore.setDocument, `staff/${user.uid}`, user);

Where user is data object for document.

**Comment by n6g7** [comment]
@TimMeade `setDocument` is indeed the solution to your problem, and not being able to provide a custom ID to the `addDocument` method is a restriction coming from the firebase SDK as the [`add`](https://firebase.google.com/docs/reference/js/firebase.firestore.CollectionReference#add) method **does** generate an ID automatically.

I'm re-opening this add a section about custom IDs in the docs. :)

**Comment by n6g7** [comment]
@TimMeade I added [a custom keys section](https://n6g7.github.io/redux-saga-firebase/guides/custom-keys) to the docs to explain how to solve your issue. :)
