### ISSUE TITLE
Add support for linking additional OAuth providers.

### ISSUE THREAD

**Issue by hhorne** [n6g7/redux-saga-firebase#90]
**Purpose**
Allow users to link and unlink additional OAuth providers to their account.

Pull request to add this: #89

**Comment by hhorne** [comment]
After issues with the last PR, this was merged in with PR #91

**Comment by n6g7** [comment]
@hhorne I released [v0.9.0](https://github.com/n6g7/redux-saga-firebase/releases/tag/v0.9.0) with these changes. Thanks a lot! 🎉
